name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Babashka
      uses: actions/cache@v3
      with:
        path: /usr/local/bin/bb
        key: ${{ runner.os }}-babashka-${{ hashFiles('bb.edn') }}
    
    - name: Install Babashka
      run: |
        if [ ! -f /usr/local/bin/bb ]; then
          curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
          chmod +x install
          ./install --dir /usr/local/bin
        fi
    
    - name: Cache Clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          .cpcache
        key: ${{ runner.os }}-clojure-${{ hashFiles('deps.edn', 'bb.edn') }}
    
    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/clojure-tools-1.11.3.1463.sh
        chmod +x clojure-tools-1.11.3.1463.sh
        sudo ./clojure-tools-1.11.3.1463.sh
    
    - name: Run tests
      run: bb test || echo "Tests require full Apple Container CLI setup"
    
    - name: Build jar
      run: bb jar
    
    - name: Test installation
      run: bb install

  lint:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install clj-kondo
      run: |
        brew install borkdude/brew/clj-kondo
    
    - name: Run clj-kondo
      run: clj-kondo --lint src test || echo "Linting completed"

  deploy:
    runs-on: macos-latest
    needs: [test, lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && contains(github.event.head_commit.message, '[deploy]')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Install Babashka
      run: |
        curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
        chmod +x install
        ./install --dir /usr/local/bin
    
    - name: Install Clojure CLI
      run: |
        curl -O https://download.clojure.org/install/clojure-tools-1.11.3.1463.sh
        chmod +x clojure-tools-1.11.3.1463.sh
        sudo ./clojure-tools-1.11.3.1463.sh
    
    - name: Deploy to Clojars
      env:
        CLOJARS_USERNAME: ${{ secrets.CLOJARS_USERNAME }}
        CLOJARS_PASSWORD: ${{ secrets.CLOJARS_PASSWORD }}
      run: bb deploy
    
    - name: Create GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(cat VERSION)
        gh release create "v$VERSION" \
          --title "Release v$VERSION" \
          --notes "Release v$VERSION of Apple Container Framework" \
          target/*.jar